name: Deploy to Netlify on commits to master
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build site
        run: yarn build
      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          REACT_APP_LAMBDA_URL=${{ secrets.NETLIFY_LAMBDA_URL }}
          REACT_APP_URL=${{ secrets.NETLIFY_APP_URL }}
        run: netlify deploy --dir=build --prod
